// Glosario de análisis financiero: una entrada por partida (clave = nombre corto `short` de data.json).
// Campos: def (qué es) · f (fórmula, HTML; usa frac(num,den)) · parts (partidas del reporte que entran en la fórmula)
//         read (cómo leerlo: alto vs bajo) · pista (qué sugiere sobre la industria) · rel (partidas relacionadas)
//         calc(get) opcional: recalcula el indicador con las partidas del reporte (get(short) -> valor de la entidad).
// Todo el texto es estático y sin cifras: las cifras vivas las pone el panel de detalle a partir de los datos.
const frac = (n, d) => `<span class="frac"><span>${n}</span><span>${d}</span></span>`;
const BASE_BAL = 'En este reporte cada partida del balance se expresa como % del total de activos (análisis vertical).';
const BASE_ER = 'En este reporte cada partida del estado de resultados se expresa como % de los ingresos (análisis vertical).';

const GLOSARIO = {
  // ---------------- Activos ----------------
  'Efectivo': {def:'Caja y equivalentes de efectivo: dinero disponible de inmediato e inversiones de altísima liquidez (vencimiento ≤ 3 meses).',
    f:frac('Efectivo y equivalentes','Total activos'), read:'Mucho efectivo da colchón y opcionalidad (adquisiciones, I+D, recompras) pero rinde poco; muy poco efectivo obliga a depender de líneas de crédito o del flujo operativo.',
    pista:'Las biotech en etapa de desarrollo acumulan efectivo de rondas de capital para financiar años de I+D sin ingresos estables. Las industrias de activo pesado (O&G) mantienen poco efectivo relativo a su enorme base de PP&E.',
    rel:['Inversiones CP','Liquidez inmediata','Razón de efectivo','Prueba ácida']},
  'Inversiones CP': {def:'Inversiones temporales/negociables con vencimiento menor a un año (bonos, papel comercial, depósitos a plazo).',
    f:frac('Inversiones de corto plazo','Total activos'), read:'Junto con el efectivo forma la "tesorería". Un saldo alto indica excedentes de caja que la empresa estaciona mientras decide en qué invertirlos.',
    pista:'Las tecnológicas muy rentables suelen estacionar grandes excedentes en inversiones temporales.',
    rel:['Efectivo','Liquidez inmediata','Prueba ácida']},
  'Cuentas por cobrar': {def:'Lo que los clientes deben por ventas a crédito (neto de estimación de cuentas incobrables).',
    f:frac('Cuentas por cobrar comerciales','Total activos'), read:'Un peso alto refleja ventas a crédito a clientes institucionales (hospitales, gobiernos, distribuidores) o plazos de pago largos; su contraparte de eficiencia son los días de cobro.',
    pista:'Pharma y las CROs (servicios a farmacéuticas) cobran a plazos largos; O&G vende commodities con cobro rápido.',
    rel:['Días de cuentas por cobrar','Prueba ácida','Total act. circulante']},
  'Inventarios': {def:'Materia prima, producto en proceso y producto terminado pendiente de vender, valuado a costo.',
    f:frac('Inventarios','Total activos'), read:'Mucho inventario inmoviliza capital de trabajo y expone a obsolescencia; un peso bajo puede indicar modelo de servicios o rotación muy rápida.',
    pista:'Pharma mantiene inventarios de muchos meses (procesos regulados, lotes largos, producto en bodega). Las CROs no tienen inventario. O&G rota muy rápido.',
    rel:['Días de inventario','Rotación de inventario','Prueba ácida']},
  'Otros act. circulantes': {def:'Activos de corto plazo no clasificados en los rubros anteriores: pagos anticipados, impuestos por recuperar, derivados de corto plazo, activos disponibles para venta.',
    f:frac('Otros activos circulantes','Total activos'), read:'Suelen ser poco informativos por sí solos; un peso alto merece revisar las notas (p. ej. impuestos por recuperar o activos en venta).',
    pista:'No es una partida típicamente distintiva entre industrias.', rel:['Total act. circulante']},
  'Total act. circulante': {def:'Suma de los activos que se espera convertir en efectivo dentro de un año.',
    f:'Efectivo + Inversiones CP + Cuentas por cobrar + Inventarios + Otros act. circulantes', parts:['Efectivo','Inversiones CP','Cuentas por cobrar','Inventarios','Otros act. circulantes'],
    calc:g=>sum(g,['Efectivo','Inversiones CP','Cuentas por cobrar','Inventarios','Otros act. circulantes']),
    read:'Un activo mayoritariamente circulante habla de un negocio "ligero" en activos fijos; uno bajo, de un negocio intensivo en capital.',
    pista:'O&G (refinación, perforación, ductos) tiene la menor proporción circulante; biotech y tecnología la mayor.',
    rel:['Total act. no circulante','Razón corriente','Capital de trabajo / Activo']},
  'Inversiones LP': {def:'Inversiones en otras compañías (asociadas, negocios conjuntos) o instrumentos financieros de largo plazo.',
    f:frac('Inversiones de largo plazo','Total activos'), read:'Indica participaciones estratégicas o tesorería invertida a largo plazo.',
    pista:'Rara vez es grande; útil como rasgo secundario.', rel:['Inversiones CP']},
  'PP&E neto': {def:'Propiedades, planta y equipo menos depreciación acumulada: el activo físico productivo.',
    f:frac('PP&E bruto − depreciación acumulada','Total activos'),
    read:'Mide la intensidad de capital. Alto = negocio de infraestructura (plantas, pozos, refinerías, fabs); bajo = negocio basado en conocimiento, marcas o patentes.',
    pista:'El rasgo más distintivo de O&G: la mayor parte de su activo es PP&E. Los fabricantes de semiconductores con fábricas propias también lo elevan; las CROs y farmacéuticas basadas en patentes lo tienen bajo.',
    rel:['Rotación de activos fijos netos','Depreciación y amortización','Intangibles']},
  'Intangibles': {def:'Activos sin sustancia física: crédito mercantil (goodwill) de adquisiciones, patentes, licencias, marcas, relaciones con clientes.',
    f:frac('Intangibles + crédito mercantil','Total activos'),
    read:'Un peso alto suele venir de adquisiciones (el goodwill es la prima pagada sobre el valor en libros) más que de I+D propia, porque la I+D interna normalmente se lleva a gasto.',
    pista:'Pharma y algunas tecnológicas cargan intangibles por compras de compañías y moléculas; las CROs por consolidación del sector. O&G casi no tiene.',
    rel:['Otros act. LP (intang. + otros)','PP&E neto','I+D']},
  'Otros act. no circulantes': {def:'Activos de largo plazo restantes: impuestos diferidos activos, derechos de uso por arrendamiento, activos por planes de pensión, etc.',
    f:frac('Otros activos no circulantes','Total activos'), read:'Revisar notas; en O&G suele incluir activos de abandono y diferidos.',
    pista:'Rasgo secundario.', rel:['Otros act. LP (intang. + otros)']},
  'Otros act. LP (intang. + otros)': {def:'Partida agregada para poder comparar con las empresas A–D: Intangibles + Otros activos no circulantes (las empresas misteriosas traen ese rubro junto).',
    f:'Intangibles + Otros act. no circulantes', parts:['Intangibles','Otros act. no circulantes'], read:'Alto = activo "no físico" (adquisiciones, patentes, impuestos diferidos).',
    pista:'Una empresa con mucho de este rubro y poco PP&E apunta a pharma/biotech o a una tecnológica adquisitiva, no a O&G.',
    rel:['Intangibles','PP&E neto']},
  'Total act. no circulante': {def:'Activos de largo plazo: PP&E, intangibles, inversiones LP y otros.',
    f:'Total activos − Total act. circulante', parts:['Total act. circulante'], calc:g=>1-g('Total act. circulante'),
    read:'Complemento del activo circulante; mide qué tan "anclado" está el capital.', pista:'Máximo en O&G.', rel:['PP&E neto','Total act. circulante']},
  'Total activos': {def:'Todo lo que la empresa controla y espera que le genere beneficios. Es la base (100%) del análisis vertical del balance.',
    f:'Pasivos + Capital', read:'Es la base, por eso vale 100% para todos.', pista:'—', rel:['Rotación de activos totales','ROA']},
  // ---------------- Pasivos ----------------
  'Cuentas por pagar': {def:'Lo que la empresa debe a proveedores por compras a crédito: financiamiento operativo "gratuito".',
    f:frac('Proveedores','Total activos'), read:'Alto = la empresa financia su operación con sus proveedores (poder de negociación o compras muy grandes).',
    pista:'O&G y refinadores compran grandes volúmenes de crudo a crédito, por eso su peso relativo es mayor.',
    rel:['Días de cuentas por pagar','Ciclo de efectivo']},
  'Deuda CP': {def:'Préstamos y papel comercial con vencimiento menor a un año, más la porción circulante de la deuda de largo plazo.',
    f:frac('Deuda de corto plazo','Total activos'), read:'Deuda que hay que pagar o refinanciar pronto: presiona la liquidez.', pista:'Rasgo secundario.',
    rel:['Deuda financiera','Razón corriente']},
  'Otros pas. circulantes': {def:'Pasivos de corto plazo no financieros: gastos acumulados, impuestos por pagar, anticipos de clientes, provisiones (p. ej. descuentos y devoluciones en pharma).',
    f:frac('Otros pasivos circulantes','Total activos'), read:'En pharma suele ser grande por provisiones de reembolsos y descuentos a aseguradoras/gobierno; en servicios, por anticipos de clientes.',
    pista:'Elevado en pharma y CROs.', rel:['Total pas. circulante']},
  'Total pas. circulante': {def:'Obligaciones con vencimiento menor a un año.',
    f:'Cuentas por pagar + Deuda CP + Otros pas. circulantes', parts:['Cuentas por pagar','Deuda CP','Otros pas. circulantes'],
    calc:g=>sum(g,['Cuentas por pagar','Deuda CP','Otros pas. circulantes']), read:'Se compara contra el activo circulante para medir liquidez.',
    pista:'—', rel:['Razón corriente','Prueba ácida','Capital de trabajo / Activo']},
  'Deuda LP': {def:'Bonos y créditos bancarios con vencimiento mayor a un año.',
    f:frac('Deuda de largo plazo','Total activos'), read:'Financiamiento estructural. Alto = estrategia apalancada (recompras, adquisiciones) o activos de larga vida financiados con deuda.',
    pista:'Pharma usa deuda para financiar adquisiciones y recompras; las tecnológicas más rentables casi no la necesitan.',
    rel:['Deuda financiera','Deuda / Capital','Cobertura de intereses']},
  'Otros pas. no circulantes': {def:'Pasivos de largo plazo no financieros: impuestos diferidos, pensiones, provisiones por abandono/retiro de activos, arrendamientos.',
    f:frac('Otros pasivos no circulantes','Total activos'), read:'Alto en industrias con obligaciones ambientales o de retiro de activos.',
    pista:'O&G registra grandes provisiones de abandono de pozos e impuestos diferidos: rasgo muy característico.',
    rel:['Total pas. no circulante']},
  'Total pas. no circulante': {def:'Obligaciones de largo plazo (financieras y no financieras).',
    f:'Deuda LP + Otros pas. no circulantes', parts:['Deuda LP','Otros pas. no circulantes'], calc:g=>sum(g,['Deuda LP','Otros pas. no circulantes']),
    read:'Financiamiento estable de largo plazo.', pista:'—', rel:['Total pasivos']},
  'Total pasivos': {def:'Todo lo que la empresa debe a terceros.',
    f:frac('Pasivo total','Total activos'), parts:['Total pas. circulante','Total pas. no circulante'], calc:g=>sum(g,['Total pas. circulante','Total pas. no circulante']),
    read:'Es el complemento del capital: qué parte del activo financian los acreedores.', pista:'Ver Nivel de endeudamiento.', rel:['Nivel de endeudamiento','Total capital']},
  // ---------------- Capital ----------------
  'Capital común': {def:'Capital aportado por los accionistas comunes más utilidades retenidas, menos acciones recompradas.',
    f:frac('Capital contable común','Total activos'), read:'Bajo puede deberse a pérdidas acumuladas o, en empresas maduras y rentables, a recompras de acciones y dividendos que encogen el capital.',
    pista:'Capital bajo + ROE muy alto suele ser señal de recompras agresivas (típico de pharma y tecnológicas maduras).',
    rel:['Total capital','Multiplicador de capital','ROE']},
  'Otro capital': {def:'Otras partidas del capital (otro resultado integral, participación no controladora, instrumentos híbridos).',
    f:frac('Otro capital','Total activos'), read:'Normalmente pequeño.', pista:'—', rel:['Total capital']},
  'Total capital': {def:'Capital contable total (incluye participación minoritaria): lo que los accionistas financian del activo.',
    f:frac('Capital contable','Total activos'), read:'Alto = financiamiento conservador; bajo = apalancado (por deuda o por haber devuelto capital vía recompras).',
    pista:'Las tecnológicas suelen ser las menos apalancadas.', rel:['Multiplicador de capital','Deuda / Capital','ROE','Nivel de endeudamiento']},
  'Pasivo + Capital': {def:'Lado derecho del balance; siempre igual al total de activos.', f:'Total pasivos + Total capital', parts:['Total pasivos','Total capital'],
    calc:g=>sum(g,['Total pasivos','Total capital']), read:'Comprobación contable (100%).', pista:'—', rel:['Total activos']},
  // ---------------- Estado de resultados ----------------
  'Ingresos': {def:'Ventas netas de bienes y servicios. Base (100%) del análisis vertical del estado de resultados.', f:'Ventas − devoluciones y descuentos',
    read:'Es la base, vale 100%.', pista:'—', rel:['Rotación de activos totales']},
  'Costo de ventas': {def:'Costo directo de producir lo vendido: materia prima, mano de obra directa, gastos de fabricación (y en commodities, el costo del crudo o gas).',
    f:frac('Costo de ventas','Ingresos'), read:'Alto = negocio de commodity o de volumen con poco poder de precio; bajo = producto diferenciado (patentes, propiedad intelectual).',
    pista:'O&G y refinación tienen el costo de ventas más alto: venden un commodity. Pharma, con patentes, el más bajo.',
    rel:['Utilidad bruta','Rotación de inventario','Días de inventario']},
  'Utilidad bruta': {def:'Lo que queda de cada peso de ventas tras el costo directo.', f:'Ingresos − Costo de ventas', parts:['Costo de ventas'], calc:g=>1-g('Costo de ventas'),
    read:'El margen bruto es la mejor medida del poder de precio del producto.', pista:'Altísimo en pharma (patentes) y en software/semiconductores de diseño.',
    rel:['Costo de ventas','Margen operacional']},
  'SG&A': {def:'Gastos de venta, generales y de administración (fuerza de ventas, marketing, corporativo), sin incluir I+D.',
    f:frac('Gastos de venta, generales y adm.','Ingresos'), read:'Alto = producto que requiere mucha promoción y fuerza comercial (visitadores médicos, marketing a médicos).',
    pista:'Pharma y CROs gastan mucho en SG&A; O&G casi nada como proporción de sus ingresos.', rel:['I+D','Total gastos operativos','Margen operacional']},
  'I+D': {def:'Investigación y desarrollo llevada a gasto en el periodo.', f:frac('Gasto en I+D','Ingresos'),
    read:'Intensidad de innovación. Es el "costo de reponer" las patentes y productos futuros.',
    pista:'Rasgo fuerte de pharma, biotech y semiconductores (> 15% de ventas). En O&G es mínimo.', rel:['SG&A','Intangibles']},
  'Otros gastos operativos': {def:'Otros gastos/ingresos operativos (deterioros, reestructuras, ganancias en venta de activos).', f:frac('Otros gastos operativos','Ingresos'),
    read:'Suelen ser partidas no recurrentes; valores negativos son ingresos.', pista:'—', rel:['Total gastos operativos']},
  'Total gastos operativos': {def:'Costo de ventas + SG&A + I+D + otros gastos operativos.', f:'Costo de ventas + SG&A + I+D + Otros gastos operativos',
    parts:['Costo de ventas','SG&A','I+D','Otros gastos operativos'], calc:g=>sum(g,['Costo de ventas','SG&A','I+D','Otros gastos operativos']),
    read:'1 − este valor ≈ margen operacional.', pista:'—', rel:['EBIT','Margen operacional']},
  'Depreciación y amortización': {def:'Asignación periódica del costo de los activos fijos (depreciación) e intangibles (amortización). Ya está incluida dentro del costo de ventas y los gastos.',
    f:frac('D&A','Ingresos'), read:'Alta = negocio intensivo en capital que debe reinvertir constantemente para mantener su base de activos.',
    pista:'O&G (agotamiento de reservas) y semiconductores con fábricas propias tienen D&A alta.', rel:['EBITDA','PP&E neto']},
  'Gasto por intereses (neto)': {def:'Intereses pagados menos intereses ganados sobre la tesorería.', f:frac('Intereses pagados − intereses ganados','Ingresos'),
    read:'Si es negativo la empresa gana más intereses de los que paga (tesorería grande).', pista:'—', rel:['Cobertura de intereses','Deuda LP']},
  'Otros (no operativos)': {def:'Ganancias/pérdidas fuera de la operación: cambiarias, en inversiones, en asociadas.', f:frac('Otros no operativos','Ingresos'),
    read:'Partidas volátiles; no reflejan el negocio central.', pista:'—', rel:['Utilidad antes de impuestos']},
  'EBIT': {def:'Utilidad antes de intereses e impuestos (utilidad operativa).', f:'Ingresos − Total gastos operativos', parts:['Total gastos operativos'], calc:g=>1-g('Total gastos operativos'),
    read:'Lo que gana la operación sin importar cómo se financia ni cuántos impuestos paga.', pista:'Ver Margen operacional.', rel:['Margen operacional','EBITDA','Cobertura de intereses']},
  'EBITDA': {def:'EBIT + depreciación y amortización: aproximación del flujo operativo antes de inversiones.', f:'EBIT + Depreciación y amortización',
    parts:['EBIT','Depreciación y amortización'], calc:g=>sum(g,['EBIT','Depreciación y amortización']),
    read:'La brecha EBITDA − EBIT muestra cuánto pesa la D&A: grande en negocios intensivos en capital.', pista:'O&G tiene la mayor brecha relativa.', rel:['EBIT','Depreciación y amortización']},
  'Utilidad antes de impuestos': {def:'EBIT menos intereses netos y otros no operativos.', f:'EBIT − Gasto por intereses (neto) − Otros (no operativos)',
    parts:['EBIT','Gasto por intereses (neto)','Otros (no operativos)'], read:'Base gravable contable.', pista:'—', rel:['Impuestos','Utilidad neta']},
  'Impuestos': {def:'Impuesto sobre la renta del periodo (corriente + diferido).', f:frac('Impuestos','Ingresos'),
    read:'La tasa efectiva (impuestos ÷ utilidad antes de impuestos) varía por jurisdicción y créditos fiscales (p. ej. por I+D).', pista:'—', rel:['Utilidad antes de impuestos']},
  'Otros (después de impuestos)': {def:'Operaciones discontinuadas, participación minoritaria y otros ajustes después de impuestos.', f:frac('Otros después de impuestos','Ingresos'),
    read:'Normalmente pequeño.', pista:'—', rel:['Utilidad neta']},
  'Utilidad neta': {def:'Lo que queda para los accionistas comunes después de todo.', f:frac('Utilidad neta','Ingresos'),
    read:'Igual al margen neto.', pista:'Ver Margen neto.', rel:['Margen neto','ROE','ROA']},
  // ---------------- Indicadores: Liquidez ----------------
  'Razón corriente': {def:'Cuántas veces el activo circulante cubre al pasivo circulante.', f:frac('Activo circulante','Pasivo circulante'),
    parts:['Total act. circulante','Total pas. circulante'], calc:g=>g('Total act. circulante')/g('Total pas. circulante'),
    read:'> 1 indica que los recursos de corto plazo alcanzan para las obligaciones de corto plazo. Muy alta (> 3) puede ser exceso de efectivo ocioso; < 1 es común en empresas con cobro rápido y poder sobre proveedores, pero también puede indicar tensión de liquidez.',
    pista:'Biotech y tecnología suelen tener razones altas (tesorería grande); O&G y pharma operan más ajustadas.',
    rel:['Prueba ácida','Razón de efectivo','Capital de trabajo / Activo']},
  'Prueba ácida': {def:'Liquidez sin depender de vender inventario: solo activos muy líquidos contra el pasivo circulante.',
    f:frac('Efectivo + Inversiones CP + Cuentas por cobrar','Pasivo circulante'), parts:['Efectivo','Inversiones CP','Cuentas por cobrar','Total pas. circulante'],
    calc:g=>sum(g,['Efectivo','Inversiones CP','Cuentas por cobrar'])/g('Total pas. circulante'),
    read:'Más exigente que la razón corriente. La diferencia entre ambas revela cuánto de la liquidez depende del inventario (y de otros circulantes).',
    pista:'Una brecha grande razón corriente − prueba ácida apunta a inventarios pesados (pharma).',
    rel:['Razón corriente','Inventarios','Razón de efectivo']},
  'Capital de trabajo neto (USD mm)': {def:'Activo circulante menos pasivo circulante, en millones de dólares.', f:'Activo circulante − Pasivo circulante',
    read:'Es una cifra absoluta: depende del tamaño de la empresa, por eso no se compara directo entre compañías de distinto tamaño. Ver la versión relativa "Capital de trabajo / Activo".',
    pista:'—', rel:['Capital de trabajo / Activo','Razón corriente']},
  // ---------------- Indicadores: Eficiencia ----------------
  'Rotación de inventario': {def:'Cuántas veces al año se vende y repone el inventario.', f:frac('Costo de ventas','Inventario promedio'),
    read:'Alta = inventario fluye rápido (commodity, perecedero, justo a tiempo). Baja = inventario de lento movimiento o procesos largos. Es el inverso de los días de inventario (365 ÷ rotación).',
    pista:'O&G rota muchísimo; pharma muy poco.', rel:['Días de inventario','Inventarios','Costo de ventas']},
  'Rotación de activos fijos netos': {def:'Cuántos pesos de ventas genera cada peso de PP&E neto.', f:frac('Ingresos','PP&E neto'),
    read:'Alta = negocio ligero en activos fijos (servicios, diseño, outsourcing). Baja = intensivo en capital.',
    pista:'Las CROs y empresas de diseño sin fábricas tienen rotaciones de activo fijo altísimas; O&G y empresas con fábricas, bajas.',
    rel:['PP&E neto','Rotación de activos totales']},
  'Rotación de activos totales': {def:'Cuántos pesos de ventas genera cada peso de activo total.', f:frac('Ingresos','Total activos'),
    read:'Es el componente de "eficiencia" del DuPont: ROA = margen neto × rotación. Alta rotación compensa márgenes bajos (negocio de volumen).',
    pista:'O&G/refinación: alta rotación con margen bajo. Pharma y tecnología: rotación baja pero margen alto.',
    rel:['ROA','ROE','Margen neto implícito','Rotación de activos fijos netos']},
  'Días de cuentas por cobrar': {def:'Días promedio que tardan los clientes en pagar (DSO).', f:frac('Cuentas por cobrar','Ingresos')+' × 365',
    read:'Más días = más capital de trabajo inmovilizado en clientes. Depende de la industria y del poder de negociación.',
    pista:'Pharma (hospitales, gobiernos, mayoristas) y CROs cobran lento; O&G cobra rápido.',
    rel:['Cuentas por cobrar','Ciclo de efectivo','Ciclo operativo']},
  'Días de inventario': {def:'Días promedio que el inventario permanece antes de venderse (DIO).', f:frac('Inventario','Costo de ventas')+' × 365',
    read:'Más días = inventario de lenta rotación (procesos largos, producto regulado, stock de seguridad).',
    pista:'Señal fuerte de pharma (cientos de días). O&G en pocas semanas. Las CROs no tienen inventario.',
    rel:['Rotación de inventario','Inventarios','Ciclo de efectivo']},
  'Días de cuentas por pagar': {def:'Días promedio que la empresa tarda en pagar a proveedores (DPO).', f:frac('Cuentas por pagar','Costo de ventas')+' × 365',
    read:'Más días = la empresa se financia con proveedores. Ojo: con costo de ventas bajo (pharma) el indicador se infla.',
    pista:'—', rel:['Cuentas por pagar','Ciclo de efectivo']},
  'Ciclo operativo': {def:'Días desde que se compra inventario hasta que se cobra la venta.', f:'Días de inventario + Días de cuentas por cobrar',
    parts:['Días de inventario','Días de cuentas por cobrar'], calc:g=>sum(g,['Días de inventario','Días de cuentas por cobrar']),
    read:'Mide qué tan largo es el proceso "producir-vender-cobrar".', pista:'Largo en pharma, corto en O&G.', rel:['Ciclo de efectivo']},
  'Ciclo de efectivo': {def:'Días que la empresa financia su operación con recursos propios (ciclo de conversión de efectivo).', f:'Días de inventario + Días de cuentas por cobrar − Días de cuentas por pagar',
    parts:['Días de inventario','Días de cuentas por cobrar','Días de cuentas por pagar'],
    calc:g=>g('Días de inventario')+g('Días de cuentas por cobrar')-g('Días de cuentas por pagar'),
    read:'Más días = más necesidad de capital de trabajo. Negativo = los proveedores financian la operación.',
    pista:'O&G casi cero; pharma muy largo.', rel:['Ciclo operativo','Días de inventario','Días de cuentas por cobrar','Días de cuentas por pagar']},
  // ---------------- Indicadores: Apalancamiento ----------------
  'Nivel de endeudamiento': {def:'Proporción del activo financiada con pasivos (deuda + pasivos operativos).', f:frac('Total pasivos','Total activos'),
    parts:['Total pasivos'], calc:g=>g('Total pasivos'),
    read:'Más alto = más riesgo financiero pero también más palanca sobre el ROE. Incluye pasivos no financieros; para deuda con costo ver "Deuda financiera".',
    pista:'Pharma suele estar más apalancada (adquisiciones y recompras); tecnología menos.',
    rel:['Total pasivos','Deuda / Capital','Multiplicador de capital']},
  'Cobertura de intereses': {def:'Cuántas veces la utilidad operativa cubre el gasto por intereses.', f:frac('EBIT','Gasto por intereses (neto)'),
    read:'> 3–5× se considera holgado. Si el gasto neto por intereses es negativo (la empresa gana más intereses de los que paga) el indicador sale negativo y NO significa riesgo: significa que no depende de deuda.',
    pista:'Negativo en biotech, tech y pharma de este ejercicio por su ingreso neto por intereses.',
    rel:['EBIT','Gasto por intereses (neto)','Deuda LP']},
  // ---------------- Indicadores: Rentabilidad ----------------
  'Margen neto': {def:'Utilidad neta por cada peso de ventas.', f:frac('Utilidad neta','Ingresos'),
    read:'Resume poder de precio, estructura de costos, financiamiento e impuestos.', pista:'Alto en pharma y tecnología; bajo en O&G/refinación.',
    rel:['Margen operacional','ROA','ROE','Margen neto implícito']},
  'Margen operacional': {def:'Utilidad operativa (EBIT) por cada peso de ventas.', f:frac('EBIT','Ingresos'),
    read:'Mide la rentabilidad del negocio antes de financiamiento e impuestos: comparable entre empresas con distinta estructura de capital.',
    pista:'Patentes y propiedad intelectual (pharma, semiconductores de diseño) dan márgenes de 30%+; commodities, de un dígito o poco más.',
    rel:['EBIT','Margen neto','Utilidad bruta','SG&A','I+D']},
  'ROA': {def:'Rendimiento sobre activos: utilidad neta por cada peso de activo.', f:frac('Utilidad neta','Total activos')+' = Margen neto × Rotación de activos totales',
    parts:['Margen neto','Rotación de activos totales'], calc:g=>g('Margen neto')*g('Rotación de activos totales'),
    read:'Combina rentabilidad y eficiencia del activo, sin el efecto del apalancamiento.', pista:'—',
    rel:['ROE','Margen neto','Rotación de activos totales','ROA implícito']},
  'ROE': {def:'Rendimiento sobre el capital de los accionistas.', f:frac('Utilidad neta','Capital contable')+' = Margen neto × Rotación de activos × Multiplicador de capital',
    parts:['Margen neto','Rotación de activos totales','Multiplicador de capital'], calc:g=>g('Margen neto')*g('Rotación de activos totales')*g('Multiplicador de capital'),
    read:'Identidad DuPont: un ROE alto puede venir de (1) margen, (2) rotación o (3) apalancamiento. El tercero es el menos "sano": un capital contable pequeño (por deuda o por recompras) infla el ROE sin que el negocio sea mejor.',
    pista:'O&G: ROE por rotación. Pharma: margen + apalancamiento. Tecnología: margen con poco apalancamiento.',
    rel:['ROA','Multiplicador de capital','Margen neto implícito','Rotación de activos totales']},
  'ROC': {def:'Rendimiento sobre el capital (variante de Refinitiv): utilidad operativa después de impuestos sobre el capital total (deuda + capital contable).',
    f:frac('EBIT × (1 − tasa de impuestos)','Deuda + Capital contable'), read:'Rendimiento del capital aportado por accionistas y acreedores. Se compara contra el costo de capital (WACC).',
    pista:'—', rel:['ROIC','ROCE']},
  'ROIC': {def:'Rendimiento sobre el capital invertido.', f:frac('NOPAT = EBIT × (1 − t)','Deuda + Capital contable − Efectivo'),
    read:'La medida más usada de creación de valor: si ROIC > WACC la empresa crea valor. Excluye el efectivo excedente para medir solo el capital operativo.',
    pista:'—', rel:['ROC','ROCE','ROE']},
  'ROCE': {def:'Rendimiento sobre el capital empleado.', f:frac('EBIT','Total activos − Pasivo circulante'),
    read:'Útil para comparar negocios intensivos en capital: mide la utilidad operativa por cada peso de financiamiento de largo plazo.',
    pista:'—', rel:['ROIC','ROC']},
  // ---------------- Derivados (calculados en esta herramienta) ----------------
  'Liquidez inmediata': {def:'Efectivo + inversiones de corto plazo como % del activo: la "tesorería" disponible.', f:'Efectivo + Inversiones CP',
    parts:['Efectivo','Inversiones CP'], read:'Mide el colchón financiero. Muy alto en empresas que financian I+D con caja o que acumulan excedentes.',
    pista:'Alto en biotech y en tecnológicas muy rentables.', rel:['Efectivo','Inversiones CP','Razón de efectivo']},
  'Deuda financiera': {def:'Deuda con costo (corto + largo plazo) como % del activo. A diferencia del nivel de endeudamiento, excluye pasivos operativos como proveedores y provisiones.',
    f:'Deuda CP + Deuda LP', parts:['Deuda CP','Deuda LP'], read:'Mide el apalancamiento financiero "real".', pista:'—', rel:['Deuda / Capital','Nivel de endeudamiento']},
  'Deuda / Capital': {def:'Deuda financiera por cada peso de capital contable (D/E).', f:frac('Deuda CP + Deuda LP','Total capital'),
    parts:['Deuda CP','Deuda LP','Total capital'], read:'> 1× significa más deuda que capital. Muy sensible cuando el capital contable es pequeño (recompras).',
    pista:'—', rel:['Deuda financiera','Multiplicador de capital']},
  'Multiplicador de capital': {def:'Activo total por cada peso de capital contable: el factor de apalancamiento del DuPont.', f:frac('Total activos','Total capital'),
    parts:['Total capital'], read:'1× = sin pasivos; 2× = la mitad del activo se financia con pasivos; 4× = capital muy delgado. Multiplica el ROA para llegar al ROE.',
    pista:'—', rel:['ROE','Total capital','Nivel de endeudamiento']},
  'Razón de efectivo': {def:'La prueba de liquidez más estricta: solo efectivo e inversiones contra el pasivo circulante.', f:frac('Efectivo + Inversiones CP','Pasivo circulante'),
    parts:['Efectivo','Inversiones CP','Total pas. circulante'], read:'> 1× = podría pagar todo el pasivo circulante hoy con su tesorería.', pista:'—',
    rel:['Prueba ácida','Razón corriente','Liquidez inmediata']},
  'Capital de trabajo / Activo': {def:'Capital de trabajo neto relativo al tamaño de la empresa (comparable entre compañías).', f:'Total act. circulante − Total pas. circulante',
    parts:['Total act. circulante','Total pas. circulante'], read:'Positivo y alto = holgura de corto plazo; negativo = el pasivo circulante financia parte del activo de largo plazo.',
    pista:'—', rel:['Razón corriente','Capital de trabajo neto (USD mm)']},
  'Margen neto implícito': {def:'Margen neto despejado de la identidad DuPont con los datos disponibles. Las empresas A–D no reportan margen neto, pero sí ROE, rotación y capital.',
    f:'ROE × '+frac('Total capital','Total activos')+' ÷ Rotación de activos totales', parts:['ROE','Total capital','Rotación de activos totales'],
    read:'Permite comparar la rentabilidad neta de A–D contra las industrias. Es aproximado: el ROE puede usar capital promedio y el reporte usa capital al cierre.',
    pista:'—', rel:['Margen neto','ROE','Margen operacional']},
  'ROA implícito': {def:'ROA despejado de la identidad DuPont: ROE × (Capital / Activo).', f:'ROE × '+frac('Total capital','Total activos'),
    parts:['ROE','Total capital'], read:'Rentabilidad del activo sin el efecto del apalancamiento.', pista:'—', rel:['ROA','ROE','Multiplicador de capital']},
};
function sum(g, ks){ let s=0; for(const k of ks){ const v=g(k); if(v==null||isNaN(v)) return null; s+=v; } return s; }
